name: ScriptRunner
main: ch.k42.scriptrunner.ScriptPlugin
version: 0.1.5
authors: [AthmosPrime]
description: Makes scripts executable from Minecraft. Scripts must reside in the plugin folder and be executable.

depend:

commands:
  sh:
    description: runs a script
    usage: /sh [script] [arg1] [arg2] ...
    permission: script.command
  bsh:
    description: runs a script but clocks further execution until script exited
    usage: /bsh [script] [arg1] [arg2] ...
    permission: script.command
permissions:
  script.*:
    description: Gives access to all script commands
    children:
      script.command: true